sonar.projectKey=jselsner_elsnerpms_AY4N0IuwfFtGl2GK4wKU
sonar.projectName=ElsnerPMS
sonar.projectVersion=0.1.0
# Define your source directories
sonar.sources=.

# Specify the language(s)
sonar.language=js,javascript

# JavaScript and/or TypeScript specific configurations
# Assuming both your client and socket code might be using JS/TS
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,socket/coverage/lcov.info

# Exclude directories that should not be analyzed (e.g., node modules, build directories)
sonar.inclusions=client/**/*,server/**/*.*,socket/**/*.*
sonar.exclusions=node_modules/**,client/build/**,server/node_modules/**,socket/node_modules/**



# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Quality Gate
sonar.qualitygate.wait=true
