module.exports = {
  resMsg: {
    GET_NOTIFICATIONS: "Notification Fetched successfully",
    PROJECT_ASSIGNED: "has assigned you the project",
    LIST_SUBSCRIBERS: "has subscribed you to the task list",
    TASK_ASSIGNED: "has assigned you the task",
    TASK_COMMENTS_ADDED: "Task comment added by",
    TASK_COMMENTS_TAGGED_USERS: "has tagged you to the task comment",
    DISCUSSION_SUBSCRIBERS: "has subscribed you to the topic",
    DISCUSSION_TAGGED_USERS: "has mentioned you to the topic comment",
    BUG_ASSIGNEE: "has assigned you the bug",
    BUG_COMMENTS: "has tagged you to the bug comment",
    TASK_LOGGED_HOURS: "has logged time in task",
    NOTE_SUBSCRIBERS: "has subscribed you to the note",
    NOTE_COMMENTS_TAGGED_USERS: "has tagged you to the note comment",
    FILE_SUBSCRIBERS: "has subscribed you to the file",
  },

  Models: {
    Employees: "employees",
    Tasks: "projecttasks",
    Projects: "projects",
    MainTasks: "projectmaintasks",
    PMSClients: "pmsclients",
    Notifications: "notifications",
    TaskComments: "comments",
    DiscussionTopics: "discussionstopics",
    DiscussionTopicsDetails: "discussionstopicsdetails",
    Bugs: "projecttaskbugs",
    BugsComments: "bugscomments",
    TaskLoggedHours: "projecttaskhourlogs",
    Notes: "notes_pms",
    NoteComments: "notescomments",
    FileUpload: "fileuploads",
  },
};
